services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=consubanco
    ports:
      - 5432:5432
    volumes:
      - ./postgres/schema.sql:/docker-entrypoint-initdb.d/schema.sql